# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
model_revision: main
tokenizer_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
torch_dtype: bfloat16

# Data training arguments
dataset_name: AI-MO/NuminaMath-TIR

dataset_configs:
- all

preprocessing_num_workers: 36

# GRPO trainer config
bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: DeepSeek-R1-Distill-Qwen-7B-GRPO
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 256
max_steps: -1
num_train_epochs: 1
output_dir: data/DeepSeek-R1-Distill-Qwen-7B-GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
